# fly.toml for ktor-api-grpc on 2025-04-18T00:30:00Z

app = "ktor-api-grpc"
primary_region = "dfw"

[build]

[env]
  REDIS_URL  = "redis://localhost:6379"

[[services]]
  internal_port = 8080
  protocol      = "tcp"

  # HTTP (insecure)
  [[services.ports]]
    port     = 80
    handlers = ["http"]

  # HTTPS (TLS + HTTP/1)
  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 50051
  protocol      = "tcp"

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http2"]

  # ensure ALPN negotiation for h2
  [services.ports.tls_options]
    alpn = ["h2"]

# VM sizing
[[vm]]
  memory     = "1gb"
  cpu_kind   = "shared"
  cpus       = 1
  memory_mb  = 1024
