# fly.toml — gRPC‑only ghostcache API
app = "ktor-api-grpc"
primary_region = "dfw"

[build]

[env]
  REDIS_URL  = "redis://localhost:6379"

[[services]]
  internal_port = 50051         # your Netty gRPC server port
  protocol      = "tcp"

  [[services.ports]]
    port     = 443              # public port
    handlers = ["tls"]          # TLS termination

  [services.ports.tls_options]
    alpn = ["h2"]               # route only HTTP/2 (gRPC) traffic

# VM size
[[vm]]
  memory_mb = 1024
  cpu_kind  = "shared"
  cpus      = 1
